name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Preparing permissions
      run: |
        chmod +x configure.sh
        chmod +x build.sh

    - name: Configuring
      run: ./configure.sh

    - name: Building
      run: ./build.sh
