name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Building
      run: |
        chmod +x configure.sh && chmod +x build.sh
        ./configure.sh
        ./build.sh
