name: Analyze and Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output: out/ClearTemp
            configure: configure.sh
            build: build.sh

          - os: windows-latest
            output: out/Debug/ClearTemp.exe
            configure: configure.ps1
            build: build.ps1
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Permissions
        run: |
          chmod +x ${{ matrix.configure }}
          chmod +x ${{ matrix.build }}

      - if: matrix.os == 'windows-latest'
        name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - if: matrix.os == 'ubuntu-latest'
        name: Configure
        run: ./${{ matrix.configure }}

      - name: Build
        run: ./${{ matrix.build }}

      - name: Test
        run: ./${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: native-executables
          path: ./${{ matrix.output }}